//! Embed `.arc/rules/*.md` — the same files arclite audits itself with — as the built-in `default`
//! ruleset: one source, derived at compile time, so the shipped rules can't drift from the repo's
//! and their version is the binary version every run log already stamps.

use std::path::Path;

/// The build's git identity: short commit sha, `-dirty` when the worktree differs — because semver
/// alone is ambiguous between releases (a dev build and the tagged release both say `0.1.10`), and
/// "which build am I actually running" must be a masthead glance, not an inference from expected
/// behavior. Best-effort: building outside a git checkout yields `unknown`, disclosed as itself.
fn build_commit() -> String {
    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .args(args)
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned())
    };
    let Some(sha) = git(&["rev-parse", "--short", "HEAD"]).filter(|s| !s.is_empty()) else {
        return "unknown".to_owned();
    };
    let dirty = git(&["status", "--porcelain"]).is_some_and(|s| !s.is_empty());
    if dirty { format!("{sha}-dirty") } else { sha }
}

fn main() {
    // Re-run when the checkout moves (branch switch, commit, staging) so the embedded identity
    // tracks; an unstaged edit alone may not retrigger — the `-dirty` flag is best-effort, and the
    // sha stays exact.
    println!("cargo::rerun-if-changed=.git/HEAD");
    println!("cargo::rerun-if-changed=.git/index");
    println!("cargo::rustc-env=ARC_BUILD_COMMIT={}", build_commit());
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let rules_dir = Path::new(&manifest).join(".arc").join("rules");
    println!("cargo::rerun-if-changed={}", rules_dir.display());

    let mut rules: Vec<(String, String)> = Vec::new();
    for entry in std::fs::read_dir(&rules_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", rules_dir.display()))
    {
        let path = entry.expect("readable rules dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        println!("cargo::rerun-if-changed={}", path.display());
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("rule file {} has a non-UTF-8 name", path.display()))
            .to_owned();
        let body = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
            .trim()
            .to_owned();
        rules.push((id, body));
    }
    assert!(
        !rules.is_empty(),
        "no rules found in {} — the built-in default ruleset would be empty",
        rules_dir.display()
    );
    // The directory yields no order; the embedded set is sorted by id so builds are reproducible.
    rules.sort();

    let mut out = String::from(
        "/// Generated by build.rs from `.arc/rules/*.md` — the built-in `default` ruleset's\n\
         /// `(id, body)` pairs, sorted by id.\n\
         static BUILTIN_RULES: &[(&str, &str)] = &[\n",
    );
    for (id, body) in &rules {
        out.push_str(&format!("    ({id:?}, {body:?}),\n"));
    }
    out.push_str("];\n");
    let dest =
        Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("builtin_rules.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}
