//! Embed `.arc/rules/*.md` — the same files arclite audits itself with — as the built-in `default`
//! ruleset: one source, derived at compile time, so the shipped rules can't drift from the repo's
//! and their version is the binary version every run log already stamps.

use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let rules_dir = Path::new(&manifest).join(".arc").join("rules");
    println!("cargo::rerun-if-changed={}", rules_dir.display());

    let mut rules: Vec<(String, String)> = Vec::new();
    for entry in std::fs::read_dir(&rules_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", rules_dir.display()))
    {
        let path = entry.expect("readable rules dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        println!("cargo::rerun-if-changed={}", path.display());
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("rule file {} has a non-UTF-8 name", path.display()))
            .to_owned();
        let body = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
            .trim()
            .to_owned();
        rules.push((id, body));
    }
    assert!(
        !rules.is_empty(),
        "no rules found in {} — the built-in default ruleset would be empty",
        rules_dir.display()
    );
    // The directory yields no order; the embedded set is sorted by id so builds are reproducible.
    rules.sort();

    let mut out = String::from(
        "/// Generated by build.rs from `.arc/rules/*.md` — the built-in `default` ruleset's\n\
         /// `(id, body)` pairs, sorted by id.\n\
         static BUILTIN_RULES: &[(&str, &str)] = &[\n",
    );
    for (id, body) in &rules {
        out.push_str(&format!("    ({id:?}, {body:?}),\n"));
    }
    out.push_str("];\n");
    let dest =
        Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("builtin_rules.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}
